<?php

namespace MR\BoxBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function orderByName($em) {

        $query = $em->createQuery(
                'SELECT u FROM MRBoxBundle:User u ORDER BY u.surname'
        );
        $users = $query->getResult();
        return $users;
    }

}
